import dynamic from "next/dynamic";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Suspense } from "react";

const Forms = dynamic(
  () => import("../components/Forms").then((it) => it.Forms),
  { ssr: false },
);

export default function Home() {
  return (
    <Suspense fallback="loading...">
      <div className={styles.container}>
        <Head>
          <title>with-jotai</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className={styles.title}>With Jotai example</h1>
        <main className={styles.main}>
          <Forms />
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </Suspense>
  );
}
